name: WSK
author: Butzlabben
version: ${project.version}

main: net.myplayplanet.wsk.WSK

api-version: 1.13

depend:
  - WorldEdit


permissions:
  wsk.*:
    default: op
    children:
      - wsk.team.*
  wsk.team.*:
    default: op
    children:
      - wsk.team.captain
      - wsk.team.remove
      - wsk.team.put
  wsk.team.captain:
    default: op
  wsk.team.remove:
    default: op
  wsk.team.put:
    default: op