name: WSK
author: Butzlabben
version: ${project.version}

main: net.myplayplanet.wsk.WSK

api-version: 1.13

loadbefore:
  - FastAsyncWorldEdit

depend:
  - WorldGuard


permissions:
  wsk.*:
    default: op
    children:
      - wsk.team.*
      - wsk.arena.*
      - wsk.bypass.*

  wsk.arena.*:
    default: op
    children:
      - wsk.arena.info
      - wsk.arena.start
      - wsk.arena.stop
      - wsk.arena.win
      - wsk.arena.draw

  wsk.arena.info:
    default: op
  wsk.arena.start:
    default: op
  wsk.arena.stop:
    default: op
  wsk.arena.draw:
    default: op
  wsk.arena.win:
    default: op

  wsk.bypass.*:
    default: op
    children:
      - wsk.bypass.move
      - wsk.bypass.build

  wsk.bypass.move:
    default: op
  wsk.bypass.build:
    default: op

  wsk.team.*:
    default: op
    children:
      - wsk.team.captain
      - wsk.team.remove
      - wsk.team.put
  wsk.team.captain:
    default: op
  wsk.team.remove:
    default: op
  wsk.team.put:
    default: op